import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'msedge',headless:true});
try {
const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});
await page.route('https://fonts.googleapis.com/**',r=>r.abort());
await page.route('https://fonts.gstatic.com/**',r=>r.abort());
let mode='error', count=0;
await page.route('https://formsubmit.co/**', async r=> { count++; await r.fulfill({status:mode==='error'?500:200,contentType:'application/json',body:JSON.stringify(mode==='activation'?{success:true,message:'Please activate your form'}:{success:true})}); });
await page.goto('http://127.0.0.1:4173/#/contributor');
await page.getByRole('button',{name:'Gửi bài viết',exact:true}).click();
assert.equal(count,0);
assert.equal(await page.locator('[aria-invalid="true"]').count(),6);
for(const [name,value] of Object.entries({name:'Nguyễn An',email:'test@example.com',title:'Bài thử',content:'Nội dung kiểm thử'})) await page.locator(`[name="${name}"]`).fill(value);
await page.locator('[name="category"]').selectOption({label:'Khác'});
await page.locator('[name="confirmation"]').check();
await page.getByRole('button',{name:'Gửi bài viết',exact:true}).click();
await page.waitForFunction(()=>document.querySelector('#form-status').textContent.includes('Không thể'));
assert.equal(await page.locator('[name="title"]').inputValue(),'Bài thử');
mode='activation';
await page.getByRole('button',{name:'Gửi bài viết',exact:true}).click();
await page.waitForFunction(()=>document.querySelector('#form-status').textContent.includes('cần được kích hoạt'));
assert.equal(await page.locator('[name="title"]').inputValue(),'Bài thử');
mode='success';
await page.getByRole('button',{name:'Gửi bài viết',exact:true}).click();
await page.waitForFunction(()=>document.querySelector('#form-status').textContent.includes('Gửi bài thành công'));
assert.equal(await page.locator('[name="title"]').inputValue(),'');
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.locator('[data-menu-toggle]').click();
await page.locator('.dropdown-toggle').click();
assert.equal(await page.locator('#contributor-menu a').count(),3);
await page.locator('#contributor-menu a[href="#/citations"]').click();
assert.equal(await page.locator('#app-page h1').textContent(),'Cách trích nguồn');
await page.reload();
assert.equal(await page.locator('#app-page h1').textContent(),'Cách trích nguồn');
await page.setViewportSize({width:1440,height:1000});
await page.goto('http://127.0.0.1:4173/#/contributor');
await page.locator('.dropdown-toggle').focus(); await page.keyboard.press('ArrowDown');
assert.equal(await page.locator('#contributor-menu').isVisible(),true);
await page.keyboard.press('Escape');
assert.equal(await page.locator('#contributor-menu').isVisible(),false);
for (const [slug, title] of [['contributor','Gửi bài viết'], ['writing-guide','Hướng dẫn viết bài'], ['citations','Cách trích nguồn']]) {
  await page.mouse.move(0, 0);
  await page.locator('.dropdown-toggle').click();
  assert.equal(await page.locator('#contributor-menu').isVisible(), true);
  await page.locator(`#contributor-menu a[href="#/${slug}"]`).click();
  await page.waitForFunction(expected => document.querySelector('#app-page h1')?.textContent === expected, title);
  assert.equal(await page.locator('#app-page').isVisible(), true);
}
await page.screenshot({path:'../formsubmit-desktop.png',fullPage:true});
console.log('PASS browser: validation, HTTP failure, activation, success, reset, mobile/desktop menus, hash reload, overflow. Requests mocked; no email sent.');
} finally {await browser.close();}
